#
# Rock R Server Dockerfile with DataSHIELD Tulip Donkey profile
#

FROM datashield/molgenis-rock-base:4.1.0

ENV DSMEDIATION_VERSION=0.0.3
ENV DSEXPOSOME_VERSION=2.0.9
ENV DSTIDYVERSE_VERSION=v1.2.2
ENV DSOMICS_VERSION=v1.0.19
ENV DSMTL_VERSION=0.9.9
ENV DSSURVIVAL_VERSION=v2.1.3
ENV DSBASE_VERSION=6.3.5

ENV ROCK_LIB=/var/lib/rock/R/library

LABEL dsMediation=${DSMEDIATION_VERSION}
LABEL dsMTL=${DSMTL_VERSION}
LABEL dsMSurvival=${DSSURVIVAL_VERSION}
LABEL dsTidyverse=${DSTIDYVERSE_VERSION}
LABEL dsExposome=${DSEXPOSOME_VERSION}
LABEL dsOmics=${DSOMICS_VERSION}
LABEL dsBase=${DSBASE_VERSION}
RUN rm -f /etc/apt/sources.list.d/*arrow* || true
RUN rm -f /etc/apt/sources.list.d/*apache* || true
RUN apt-get update
COPY install.R /tmp/install.R

RUN --mount=type=cache,target=/root/.cache/R \
    --mount=type=cache,target=/tmp/downloaded_packages \
    Rscript /tmp/install.R \
 && chown -R rock ${ROCK_LIB}
